/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Security } from "./Security";
import { SecurityCountArgs } from "./SecurityCountArgs";
import { SecurityFindManyArgs } from "./SecurityFindManyArgs";
import { SecurityFindUniqueArgs } from "./SecurityFindUniqueArgs";
import { DeleteSecurityArgs } from "./DeleteSecurityArgs";
import { SecurityService } from "../security.service";
@graphql.Resolver(() => Security)
export class SecurityResolverBase {
  constructor(protected readonly service: SecurityService) {}

  async _securitiesMeta(
    @graphql.Args() args: SecurityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Security])
  async securities(
    @graphql.Args() args: SecurityFindManyArgs
  ): Promise<Security[]> {
    return this.service.securities(args);
  }

  @graphql.Query(() => Security, { nullable: true })
  async security(
    @graphql.Args() args: SecurityFindUniqueArgs
  ): Promise<Security | null> {
    const result = await this.service.security(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Security)
  async deleteSecurity(
    @graphql.Args() args: DeleteSecurityArgs
  ): Promise<Security | null> {
    try {
      return await this.service.deleteSecurity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
