/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SecurityService } from "../security.service";
import { SecurityCreateInput } from "./SecurityCreateInput";
import { Security } from "./Security";
import { SecurityFindManyArgs } from "./SecurityFindManyArgs";
import { SecurityWhereUniqueInput } from "./SecurityWhereUniqueInput";
import { SecurityUpdateInput } from "./SecurityUpdateInput";

export class SecurityControllerBase {
  constructor(protected readonly service: SecurityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Security })
  async createSecurity(
    @common.Body() data: SecurityCreateInput
  ): Promise<Security> {
    return await this.service.createSecurity({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Security] })
  @ApiNestedQuery(SecurityFindManyArgs)
  async securities(@common.Req() request: Request): Promise<Security[]> {
    const args = plainToClass(SecurityFindManyArgs, request.query);
    return this.service.securities({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Security })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async security(
    @common.Param() params: SecurityWhereUniqueInput
  ): Promise<Security | null> {
    const result = await this.service.security({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Security })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSecurity(
    @common.Param() params: SecurityWhereUniqueInput,
    @common.Body() data: SecurityUpdateInput
  ): Promise<Security | null> {
    try {
      return await this.service.updateSecurity({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Security })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSecurity(
    @common.Param() params: SecurityWhereUniqueInput
  ): Promise<Security | null> {
    try {
      return await this.service.deleteSecurity({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
