/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Financial } from "./Financial";
import { FinancialCountArgs } from "./FinancialCountArgs";
import { FinancialFindManyArgs } from "./FinancialFindManyArgs";
import { FinancialFindUniqueArgs } from "./FinancialFindUniqueArgs";
import { DeleteFinancialArgs } from "./DeleteFinancialArgs";
import { FinancialService } from "../financial.service";
@graphql.Resolver(() => Financial)
export class FinancialResolverBase {
  constructor(protected readonly service: FinancialService) {}

  async _financialsMeta(
    @graphql.Args() args: FinancialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Financial])
  async financials(
    @graphql.Args() args: FinancialFindManyArgs
  ): Promise<Financial[]> {
    return this.service.financials(args);
  }

  @graphql.Query(() => Financial, { nullable: true })
  async financial(
    @graphql.Args() args: FinancialFindUniqueArgs
  ): Promise<Financial | null> {
    const result = await this.service.financial(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Financial)
  async deleteFinancial(
    @graphql.Args() args: DeleteFinancialArgs
  ): Promise<Financial | null> {
    try {
      return await this.service.deleteFinancial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
